services:
  db:
    image: postgres:13-alpine
    container_name: database_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  postgres-data: