services:
  db:
    image: postgres:13-alpine
    container_name: user_info_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_INFO_USER}
      POSTGRES_PASSWORD: ${USER_INFO_PASS}
      POSTGRES_DB: ${USER_INFO_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data: